backend:
  name: github
  repo: bgopikrishna/bgopikrishna.github.io
  branch: development

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: 'src/blog/'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        allow_add: true
        default: []
      - { name: Description, label: description }
      - { name: body, label: Body, widget: markdown }
     
